// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_AKoirtf1ON2-YhPoj67T1ID8IIeEwzU',
    appId: '1:579736019531:web:dc3a8363498d787ade63ce',
    messagingSenderId: '579736019531',
    projectId: 'flutter-recipe-5393f',
    authDomain: 'flutter-recipe-5393f.firebaseapp.com',
    storageBucket: 'flutter-recipe-5393f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUg_ileF7P26nDwZ7jemw1G0fxbHm0N2A',
    appId: '1:579736019531:android:62c4ede2609566bade63ce',
    messagingSenderId: '579736019531',
    projectId: 'flutter-recipe-5393f',
    storageBucket: 'flutter-recipe-5393f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyBqUd-LJGZW5ux7xGP34L2hhiejk7mI',
    appId: '1:579736019531:ios:37c9471359a0727fde63ce',
    messagingSenderId: '579736019531',
    projectId: 'flutter-recipe-5393f',
    storageBucket: 'flutter-recipe-5393f.firebasestorage.app',
    iosClientId: '579736019531-5uq0abebghknrtsdq9mnnrn1916ae0bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ladleRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWyBqUd-LJGZW5ux7xGP34L2hhiejk7mI',
    appId: '1:579736019531:ios:37c9471359a0727fde63ce',
    messagingSenderId: '579736019531',
    projectId: 'flutter-recipe-5393f',
    storageBucket: 'flutter-recipe-5393f.firebasestorage.app',
    iosClientId: '579736019531-5uq0abebghknrtsdq9mnnrn1916ae0bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ladleRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_AKoirtf1ON2-YhPoj67T1ID8IIeEwzU',
    appId: '1:579736019531:web:5688c119fdd7bfa9de63ce',
    messagingSenderId: '579736019531',
    projectId: 'flutter-recipe-5393f',
    authDomain: 'flutter-recipe-5393f.firebaseapp.com',
    storageBucket: 'flutter-recipe-5393f.firebasestorage.app',
  );
}
